# Generated by Django 4.0.5 on 2022-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('cars', models.IntegerField()),
                ('buses', models.IntegerField()),
                ('lorries', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
