# Generated by Django 4.0.5 on 2022-07-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borders',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='borders',
            name='buses',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borders',
            name='cars',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borders',
            name='lorries',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borders',
            name='text',
            field=models.TextField(max_length=1600),
        ),
    ]
