# Generated by Django 4.0.5 on 2022-07-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_borders_time_alter_borders_buses_alter_borders_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borders',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
